M48
; DRILL file {KiCad (6.0.7)} date Sun May 28 23:18:49 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-28T23:18:49-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0669
%
G90
G05
T1
X3.9606Y-3.8583
X3.9606Y-4.0157
T2
X5.4429Y-3.937
X5.7185Y-3.937
T0
M30
