M48
; DRILL file {KiCad (6.0.7)} date Tue Jun 20 16:23:13 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-20T16:23:13-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0551
%
G90
G05
T1
X3.8795Y-3.8232
X3.8795Y-4.0508
T2
X5.4823Y-3.937
X5.7185Y-3.937
T0
M30
