M48
; DRILL file {KiCad 9.0.0} date 2025-06-05T15:48:40-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-05T15:48:40-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X98.25Y-97.11
X98.25Y-102.89
T2
X139.9Y-100.0
X146.9Y-100.0
M30
